{% set name = "huggingface_hub" %}
{% set version = "0.31.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7053561376ed7f6ffdaecf09cc54d70dc784ac6315fa4bb9b93e19662b029675

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - filelock
    - fsspec >=2023.5.0
    - packaging >=20.9
    - pyyaml >=5.1
    - requests
    - tqdm >=4.42.1
    - typing-extensions >=3.7.4.3
  run_constrained:
    # cli
    - inquirerpy ==0.3.4
    # hf_transfer
    - hf_transfer>=0.1.4
    # fastai
    - fastai >=2.4   # extra:fastai
    - fastcore >=1.3.27     # extra:fastai
    # tensorflow-testing
    - keras <3.0
    - InquirerPy ==0.3.4   # extra:cli
    - typing-extensions >=4.8.0 # extra:typing
  run_constrained_hf:
    - hf_transfer >=0.1.4   # extra:transfer
    - hf-xet >=1.1.1,<2.0.0   # extra:xet

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  requires:
    - pip
  commands:
    - pip check
    - huggingface-cli --help

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
  description: |
    The huggingface_hub is a client library to interact with the Hugging Face Hub. The Hugging Face Hub is a platform with over 35K models, 4K datasets, and 2K demos in which people can easily collaborate in their ML workflows. The Hub works as a central place where anyone can share, explore, discover, and experiment with open-source Machine Learning.

    With huggingface_hub, you can easily download and upload models, datasets, and Spaces. You can extract useful information from the Hub, and do much more. Some example use cases:

    - Downloading and caching files from a Hub repository.
    - Creating repositories and uploading an updated model every few epochs.
    - Extract metadata from all models that match certain criteria (e.g. models for text-classification).
    - List all files from a specific repository.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://huggingface.co/docs/hub/index
  dev_url: https://github.com/huggingface/huggingface_hub


extra:
  recipe-maintainers:
    - BastianZim
