{% set name = "huggingface_hub" %}
{% set version = "0.0.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/huggingface_hub-{{ version }}.tar.gz
  sha256: 616b375ae92928d73d19326b663b2241d6cd79acf60e12167eb5311d73f804fa

build:
  number: 0
  noarch: python
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.0
  run:
    - filelock
    - python >=3.6.0
    - packaging >=20.9
    - requests
    - ruamel.yaml ==0.17.16
    - tqdm
    - typing-extensions
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib_metadata

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
