{% set name = "huggingface_hub" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/huggingface_hub-{{ version }}.tar.gz
  sha256: 5c188d5b16bec4b78449f8681f9975ff9d321c16046cc29bcf0d7e464ff29276

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - filelock
    - requests
    - tqdm
    - pyyaml >=5.1
    - typing-extensions >=3.7.4.3
    - importlib-metadata  # [py<38]
    - packaging >=20.9

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
