{% set name = "huggingface_hub" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8be6f468da4470db48351e8c77d6d8115dff9b3daeb30276e568767b1ff7574

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]
  entry_points:
    - hf=huggingface_hub.cli.hf:main
    - tiny-agents=huggingface_hub.inference._mcp.cli:app

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - filelock
    - fsspec >=2023.5.0
    - hf-xet >=1.2.0,<2.0.0
    - httpx >=0.23.0,<1
    - packaging >=20.9
    - pyyaml >=5.1
    - shellingham
    - tqdm >=4.42.1
    - typer-slim
    - typing-extensions >=4.1.0
  run_constrained:
    # extras["oauth"]
    - authlib>=1.3.2
    # extras["fastai"]
    - fastai >=2.4 
    - fastcore >=1.3.27
    # extras["mcp"]
    - mcp >=1.8.0
    # extras["gradio"]
    - gradio >=5.0.0  # [py>=310]
    # extras["quality"]
    - ruff >=0.9.0
    - mypy ==1.15.0
    - libcst >=1.4.0

{% set test_skip = "" %}
{% set test_skip = test_skip + " --ignore=tests/test_hf_file_system.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_hf_api.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_utils_assets.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_utils_cache.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_commit_scheduler.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_file_download.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_hub_mixin.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_repocard.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_utils_git_credentials.py" %}
{% set test_skip = test_skip + " --ignore=tests/test_cache_no_symlinks.py" %}
{% set test_skip = test_skip + " --deselect=tests/test_oauth.py::test_oauth_not_logged_in" %}
{% set test_skip = test_skip + " --deselect=tests/test_oauth.py::test_oauth_workflow" %}
{% set test_skip = test_skip + " --deselect=tests/test_oauth.py::test_get_mocked_oauth_info" %}
{% set test_skip = test_skip + " --deselect=tests/test_cache_layout.py::ReferenceUpdates::test_update_reference" %}
{% set test_skip = test_skip + " --deselect=tests/test_snapshot_download.py::SnapshotDownloadTests::test_download_model" %}
{% set test_skip = test_skip + " --deselect=tests/test_snapshot_download.py::SnapshotDownloadTests::test_download_private_model" %}
{% set test_skip = test_skip + " --deselect=tests/test_snapshot_download.py::SnapshotDownloadTests::test_download_to_local_dir" %}
{% set test_skip = test_skip + " --deselect=tests/test_snapshot_download.py::SnapshotDownloadTests::test_offline_mode_with_cache_and_empty_local_dir" %}
{% set test_skip = test_skip + " --deselect=tests/test_utils_http.py::test_async_client_get_request" %}
{% set test_skip = test_skip + " --deselect=tests/test_utils_http.py::test_raise_on_status_async_non_stream" %}
{% set test_skip = test_skip + " --deselect=tests/test_utils_http.py::test_raise_on_status_async_stream" %}
{% set test_skip = test_skip + " --deselect=tests/test_utils_telemetry.py::TestSendTelemetry::test_topic_multiple" %}
{% set test_skip = test_skip + " --deselect=tests/test_utils_telemetry.py::TestSendTelemetry::test_topic_normal" %}
{% set test_skip = test_skip + " --deselect=tests/test_utils_telemetry.py::TestSendTelemetry::test_topic_quoted" %}
{% set test_skip = test_skip + " --deselect=tests/test_utils_telemetry.py::TestSendTelemetry::test_topic_with_subtopic" %}
#{% set test_skip = test_skip + " --deselect=tests/test_xet_upload.py::TestXetUpload::test_upload_file" %}
#{% set test_skip = test_skip + " --deselect=tests/test_xet_upload.py::TestXetUpload::test_upload_file_with_bytesio" %}
#{% set test_skip = test_skip + " --deselect=tests/test_xet_upload.py::TestXetUpload::test_upload_file_with_byte_array" %}
#{% set test_skip = test_skip + " --deselect=tests/test_xet_upload.py::TestXetUpload::test_upload_folder" %}
#{% set test_skip = test_skip + " --deselect=tests/test_xet_upload.py::TestXetUpload::test_upload_folder_create_pr" %}
#{% set test_skip = test_skip + " --deselect=tests/test_xet_upload.py::TestXetLargeUpload::test_upload_large_folder" %}
{% set test_skip = test_skip + " --ignore=tests/test_xet_upload.py" %}

{% set test_skip = test_skip + " --deselect=tests/test_inference_async_client.py::test_async_generate_timeout_error" %}
{% set test_skip = test_skip + " --deselect=tests/test_inference_async_client.py::test_use_async_with_inference_client" %}
{% set test_skip = test_skip + " --deselect=tests/test_inference_providers.py::TestHFInferenceProvider::test_check_supported_task_scenarios" %}

# Flaky on OSX CI
{% set test_skip = test_skip + " --deselect=tests/test_inference_endpoints.py::test_wait_timeout" %}  # [osx]
{% set test_skip = test_skip + " --deselect=tests/test_utils_fixes.py::TestWeakFileLock::test_lock_log_every" %}  # [osx]
{% set test_skip = test_skip + " --deselect=tests/test_utils_http.py::TestHttpBackoff::test_backoff_on_429_uses_ratelimit_header" %}  # [osx]
{% set test_skip = test_skip + " --deselect=tests/test_utils_http.py::TestHttpBackoff::test_backoff_sleep_time" %}  # [osx]


test:
  imports:
    - huggingface_hub
    - huggingface_hub._commit_api
    - huggingface_hub._commit_scheduler
    - huggingface_hub._local_folder
    - huggingface_hub._login
    - huggingface_hub._oauth
    - huggingface_hub._snapshot_download
    - huggingface_hub._space_api
    - huggingface_hub._upload_large_folder
    - huggingface_hub.cli.auth
    - huggingface_hub.cli.cache
    - huggingface_hub.cli.download
    - huggingface_hub.cli.jobs
    - huggingface_hub.cli.lfs
    - huggingface_hub.cli.repo
    - huggingface_hub.cli.repo_files
    - huggingface_hub.cli.system
    - huggingface_hub.cli.upload
    - huggingface_hub.cli.upload_large_folder
    - huggingface_hub.community
    - huggingface_hub.constants
    - huggingface_hub.dataclasses
    - huggingface_hub.errors
    - huggingface_hub.fastai_utils
    - huggingface_hub.file_download
    - huggingface_hub.hf_api
    - huggingface_hub.hf_file_system
    - huggingface_hub.hub_mixin
    - huggingface_hub.inference._client
    - huggingface_hub.inference._common
    - huggingface_hub.inference._generated
    - huggingface_hub.inference._generated.types
    - huggingface_hub.inference._generated.types.base
    - huggingface_hub.inference._generated.types.chat_completion
    - huggingface_hub.inference._providers
    - huggingface_hub.inference._providers._common
    - huggingface_hub.inference._providers.black_forest_labs
    - huggingface_hub.inference._providers.cohere
    - huggingface_hub.inference._providers.fal_ai
    - huggingface_hub.inference._providers.featherless_ai
    - huggingface_hub.inference._providers.fireworks_ai
    - huggingface_hub.inference._providers.groq
    - huggingface_hub.inference._providers.hf_inference
    - huggingface_hub.inference._providers.hyperbolic
    - huggingface_hub.inference._providers.nebius
    - huggingface_hub.inference._providers.novita
    - huggingface_hub.inference._providers.nscale
    - huggingface_hub.inference._providers.openai
    - huggingface_hub.inference._providers.replicate
    - huggingface_hub.inference._providers.sambanova
    - huggingface_hub.inference._providers.together
    - huggingface_hub.lfs
    - huggingface_hub.repocard
    - huggingface_hub.repocard_data
    - huggingface_hub.serialization
    - huggingface_hub.serialization._base
    - huggingface_hub.serialization._dduf
    - huggingface_hub.serialization._torch
    - huggingface_hub.utils
    - huggingface_hub.utils._auth
    - huggingface_hub.utils._cache_manager
    - huggingface_hub.utils._chunk_utils
    - huggingface_hub.utils._datetime
    - huggingface_hub.utils._deprecation
    - huggingface_hub.utils._dotenv
    - huggingface_hub.utils._git_credential
    - huggingface_hub.utils._headers
    - huggingface_hub.utils._http
    - huggingface_hub.utils._lfs
    - huggingface_hub.utils._pagination
    - huggingface_hub.utils._runtime
    - huggingface_hub.utils._telemetry
    - huggingface_hub.utils._typing
    - huggingface_hub.utils._xet
    - huggingface_hub.utils.endpoint_helpers
    - huggingface_hub.utils.logging
    - huggingface_hub.utils.sha
  source_files:
    - tests
  requires:
    - pip
    - pytest >=8.4.2
    - pytest-mock
    - jedi
    - numpy
    - fastapi
    - pillow
    - git
    - git-lfs
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - hf --help
    - tiny-agents --help
    # Tests take too long Windows CI and end up timing out
    - pytest --import-mode=importlib {{ test_skip }} -vv tests  # [not win]

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
  description: |
    The huggingface_hub is a client library to interact with the Hugging Face Hub. The Hugging Face Hub is a platform with over 35K models, 4K datasets, and 2K demos in which people can easily collaborate in their ML workflows. The Hub works as a central place where anyone can share, explore, discover, and experiment with open-source Machine Learning.

    With huggingface_hub, you can easily download and upload models, datasets, and Spaces. You can extract useful information from the Hub, and do much more. Some example use cases:

    - Downloading and caching files from a Hub repository.
    - Creating repositories and uploading an updated model every few epochs.
    - Extract metadata from all models that match certain criteria (e.g. models for text-classification).
    - List all files from a specific repository.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://huggingface.co/docs/huggingface_hub
  dev_url: https://github.com/huggingface/huggingface_hub


extra:
  recipe-maintainers:
    - BastianZim
